# Generated by Django 3.2.8 on 2022-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickSignDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(blank=True, default=None, max_length=350, null=True, verbose_name='Document Key')),
                ('document_path', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Document Key')),
                ('document_name', models.CharField(blank=True, default=None, max_length=75, null=True, verbose_name='Document Key')),
                ('status', models.BooleanField(default=False)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('coleta_id', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'registros_documents',
            },
        ),
        migrations.AddIndex(
            model_name='clicksigndb',
            index=models.Index(fields=['coleta_id'], name='registros_d_coleta__526459_idx'),
        ),
    ]
