# Generated by Django 3.2.8 on 2022-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('perfil', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('data_regis', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['id'], name='users_id_6a15a7_idx'),
        ),
    ]
