# Generated by Django 3.2.8 on 2022-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionScheduleDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_p', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'collection_schedule',
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agendamento_f', models.IntegerField(blank=True, default=None, null=True)),
                ('data_inc_proc_f', models.DateField(blank=True, default=None, null=True, verbose_name='Data Inicio Processo')),
                ('status_exame_f', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Status Exame')),
                ('resp_inicio_p_f', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Responsavel Inicio')),
                ('val_alvaro_f', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Valor Alvaro')),
                ('val_work_f', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Valor Work')),
                ('val_pag_f', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Valor Pagamento')),
                ('porcentagem_paga_f', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Porcentagem Paga')),
                ('data_repasse', models.DateField(blank=True, default=None, null=True, verbose_name='Data Repasse')),
                ('nf_f', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Nota Fiscal')),
                ('data_final_f', models.DateField(blank=True, default=None, null=True, verbose_name='Data Final')),
                ('data_registro_f', models.DateField(blank=True, default=None, null=True, verbose_name='Data Registro')),
                ('resp_final_p_f', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Responsavel Final')),
            ],
            options={
                'db_table': 'completed_exams',
            },
        ),
        migrations.CreateModel(
            name='PatientsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_p', models.IntegerField(blank=True, default=None, null=True)),
                ('company_p', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='RegisterActions',
            fields=[
                ('id_register', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pagina', models.IntegerField(blank=True, default=None, null=True)),
                ('id_agendamento', models.IntegerField(blank=True, default=None, null=True)),
                ('tp_operacao', models.CharField(blank=True, default='', max_length=45, null=True)),
                ('nome_user', models.CharField(blank=True, default='', max_length=45, null=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=45, null=True)),
                ('data_operacao', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'register_actions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.IntegerField(blank=True, default=None, null=True)),
                ('cpf', models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='CPF')),
            ],
            options={
                'db_table': 'auth_users.users',
            },
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['cpf'], name='auth_users._cpf_33d80d_idx'),
        ),
        migrations.AddIndex(
            model_name='registeractions',
            index=models.Index(fields=['id_agendamento'], name='register_ac_id_agen_70b351_idx'),
        ),
        migrations.AddIndex(
            model_name='patientsdb',
            index=models.Index(fields=['id_p'], name='patients_id_p_7db902_idx'),
        ),
        migrations.AddIndex(
            model_name='exams',
            index=models.Index(fields=['id_agendamento_f'], name='completed_e_id_agen_2e14d6_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionscheduledb',
            index=models.Index(fields=['id'], name='collection__id_5a0b3e_idx'),
        ),
    ]
